localization_node:
  ros__parameters:
    use_sim_time: true
    num_particles: 250
    motion_alphas: [0.15, 0.05, 0.1, 0.05]
    scan_step: 12
    hit_bonus: 2.0
    miss_penalty: 1.0
    weight_scale: 0.35
    min_weight: 1.0e-6
    occ_threshold: 50
    initial_std_xy: 0.15
    initial_std_theta: 0.35
    map_frame: map
    odom_frame: calc_odom
    base_frame: base_footprint
    scan_topic: scan
    odom_topic: calc_odom
    map_topic: map

planner_node:
  ros__parameters:
    use_sim_time: true
    obstacle_threshold: 50
    inflation_radius: 0.12
    connect_8: true
    max_search_m: 25.0
    plan_rate: 0.5
    pose_topic: /amcl_pose
    goal_topic: /goal_pose
    map_topic: /map
    path_topic: /plan
    replan_topic: /replan
    dynamic_obstacle_radius: 0.145
    dynamic_obstacle_timeout: 20.0
    start_dynamic_ignore_radius: 0.3
    replan_cooldown: 0.8
    dynamic_block_margin: 1.1

map_loader_node:
  ros__parameters:
    use_sim_time: true
    map_yaml: ~/TPF-PRA-LopezVilaclara-Vulcano/maps/generated_map.yaml
    frame_id: map
    publish_rate: 1.0

controller_node:
  ros__parameters:
    use_sim_time: true
    max_linear_speed: 0.12
    max_angular_speed: 0.14
    lookahead_distance: 0.25
    goal_tolerance: 0.12
    angle_tolerance: 0.25
    rotate_in_place_angle: 0.35
    obstacle_stop_distance: 0.20
    obstacle_clear_distance: 0.28
    obstacle_turn_speed: 0.4
    obstacle_front_angle: 0.8
    obstacle_stuck_time: 2.0
    obstacle_avoid_speed: 0.05
    obstacle_mark_cooldown: 0.5
    obstacle_publish_step: 5
    replan_distance_threshold: 0.25
    replan_angle_threshold: 0.6
    k_angular: 1.6
    k_linear: 0.6
    control_rate: 20.0
    path_topic: /plan
    pose_topic: /amcl_pose
    cmd_topic: /cmd_vel
    scan_topic: /scan
    replan_topic: /replan
