slam_node:
  ros__parameters:
    use_sim_time: true
    resolution: 0.05
    width: 400
    height: 400
    origin_x: -10.0
    origin_y: -10.0
    occupied_log: 0.85
    free_log: -0.4
    log_min: -5.0
    log_max: 5.0

explorer_node:
  ros__parameters:
    use_sim_time: true
    linear_speed: 0.15
    angular_speed: 0.8
    obstacle_distance: 0.5
    side_angle: 1.0

map_saver_node:
  ros__parameters:
    use_sim_time: true
    map_path: ~/ros2_ws/maps/generated_map
